version: '3'
services:
  database:
    build: ./database
    volumes:
      - ./database:/database
    ports:
      - 5000:3306
    working_dir: /database

  interrogator:
    build: ./interrogator
    volumes:
      - ./interrogator:/interrogator
    #ports:
    #  - TODO
    working_dir: /interrogator
